export default Object.freeze({
  ACCOUNT: "Account",
  ACTIVITY: "ActivityLog",
  APP: "App",
  AUTH: "LandingAuth",
  FORGOTPASSWORD: "ForgotPassword",
  HOME: "Home",
  LANDING: "Landing",
  LOGIN: "Login",
  PEOPLE: "People",
  SIGNUPCREATE: "SignupCreate",
  SIGNUPFULLNAME: "SignupFullName",
  SIGNUPPASSWORD: "SignupPassword",
  SIGNUPUSERNAME: "SignupUsername",
  SIGNUPVERIFY: "SignupVerify",
  TRANSACTCONFIRM: "ConfirmTransaction",
  TRANSACTHOME: "Transaction",
  TRANSACTIONDETAIL: "TransactionDetails",
  TRANSACTSELECTUSER: "TransactionSelectUser",
});
