export default Object.freeze({
  ACCOUNT: "Account",
  ACTIVITY: "ActivityLog",
  FORGOTPASSWORD: "ForgotPassword",
  HOME: "Home",
  LANDING: "Landing",
  LOGIN: "Login",
  PEOPLEHOME: "People",
  PEOPLEFRIENDS: "PeopleFriends",
  PEOPLESPLIT: "PeopleSplit",
  SIGNUPFULLNAME: "SignupFullName",
  SIGNUPIDENTIFIER: "SignupIdentifier",
  SIGNUPPASSWORD: "SignupPassword",
  SIGNUPUSERNAME: "SignupUsername",
  SIGNUPVERIFY: "SignupVerify",
  SIGNUPGENERATEWALLET: "SignupGenerateWallet",
  SIGNUPCOMPLETE: "SignupComplete",
  TRANSACTCONFIRM: "ConfirmTransaction",
  TRANSACTHOME: "Transaction",
  TRANSACTIONDETAIL: "TransactionDetails",
  TRANSACTSELECTUSER: "TransactionSelectUser",
  USERPROFILE: "UserProfile",
  APPTABS: "AppTabs",
  ROOT: "Root",
  TESTING: "Testing",
  TESTNOTIFICATIONS: "TestNotifications",
});
